
version: "2"

services:
  mongo:
    image: "mongo"
    container_name: "mongo"
    ports:
      - "27017:27017"

  # redis:
  #   image: "redis"
  #   container_name: "redis"
  #   ports:
  #     - "6379:6379"
